[package]
name = "dcdt-safe-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.dcdt-safe]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "=0.52.3"
default-features = false
