[workspace]
members = [
  "bridge-proxy",
  "bridge-proxy/meta",
  "dcdt-safe",
  "dcdt-safe/meta",
  "multi-transfer-dcdt",
  "multi-transfer-dcdt/meta",
  "multisig",
  "multisig/meta",
  "bridged-tokens-wrapper",
  "bridged-tokens-wrapper/meta",
  "test-caller",
  "test-caller/meta"
]
