[package]
name = "max-bridged-amount-module"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"

[dependencies.dharitri-sc]
version = "=0.52.3"

[dev-dependencies.dharitri-sc-scenario]
version = "=0.52.3"
