// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    multi_transfer_dcdt
    (
        init => init
        upgrade => upgrade
        batchTransferDcdtToken => batch_transfer_dcdt_token
        moveRefundBatchToSafe => move_refund_batch_to_safe
        setWrappingContractAddress => set_wrapping_contract_address
        setBridgeProxyContractAddress => set_bridge_proxy_contract_address
        addUnprocessedRefundTxToBatch => add_unprocessed_refund_tx_to_batch
        setDcdtSafeContractAddress => set_dcdt_safe_contract_address
        getWrappingContractAddress => wrapping_contract_address
        getBridgeProxyContractAddress => bridge_proxy_contract_address
        getDcdtSafeContractAddress => dcdt_safe_contract_address
        setMaxTxBatchSize => set_max_tx_batch_size
        setMaxTxBatchBlockDuration => set_max_tx_batch_block_duration
        getCurrentTxBatch => get_current_tx_batch
        getFirstBatchAnyStatus => get_first_batch_any_status
        getBatch => get_batch
        getBatchStatus => get_batch_status
        getFirstBatchId => first_batch_id
        getLastBatchId => last_batch_id
        setMaxBridgedAmount => set_max_bridged_amount
        getMaxBridgedAmount => max_bridged_amount
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
