[package]
name = "transaction"
version = "0.0.0"
authors = ["Dharitri <contact@dharitri.org>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.eth-address]
path = "../eth-address"

[dependencies.dharitri-sc]
version = "=0.52.3"
