[settings]

[[proxy]]
path = "../multi-transfer-dcdt/src/bridge_proxy_contract_proxy.rs"

[[proxy]]
path = "../multisig/src/bridge_proxy_contract_proxy.rs"

[[proxy]]
path = "./src/bridge_proxy_contract_proxy.rs"