// Code generated by the dharitri-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           74
// Async Callback (empty):               1
// Total number of exported functions:  77

#![no_std]

dharitri_sc_wasm_adapter::allocator!();
dharitri_sc_wasm_adapter::panic_handler!();

dharitri_sc_wasm_adapter::endpoints! {
    multisig
    (
        init => init
        upgrade => upgrade
        distributeFeesFromChildContracts => distribute_fees_from_child_contracts
        stake => stake
        unstake => unstake
        proposeDcdtSafeSetCurrentTransactionBatchStatus => propose_dcdt_safe_set_current_transaction_batch_status
        proposeMultiTransferDcdtBatch => propose_multi_transfer_dcdt_batch
        moveRefundBatchToSafeFromChildContract => move_refund_batch_to_safe_from_child_contract
        initSupplyFromChildContract => init_supply_from_child_contract
        addUnprocessedRefundTxToBatch => add_unprocessed_refund_tx_to_batch
        withdrawRefundFeesForEthereum => withdraw_refund_fees_for_ethereum
        withdrawTransactionFees => withdraw_transaction_fees
        withdrawSlashedAmount => withdraw_slashed_amount
        performAction => perform_action_endpoint
        sign => sign
        upgradeChildContractFromSource => upgrade_child_contract_from_source
        addBoardMember => add_board_member_endpoint
        removeUser => remove_user
        slashBoardMember => slash_board_member
        changeQuorum => change_quorum
        addMapping => add_mapping
        clearMapping => clear_mapping
        pauseDcdtSafe => pause_dcdt_safe
        unpauseDcdtSafe => unpause_dcdt_safe
        initSupplyDcdtSafe => init_supply_dcdt_safe
        initSupplyMintBurnDcdtSafe => init_supply_mint_burn_dcdt_safe
        pauseProxy => pause_proxy
        unpauseProxy => unpause_proxy
        changeFeeEstimatorContractAddress => change_fee_estimator_contract_address
        changeDharitriToEthGasLimit => change_dharitri_to_eth_gas_limit
        changeDefaultPricePerGasUnit => change_default_price_per_gas_unit
        changeTokenTicker => change_token_ticker
        dcdtSafeAddTokenToWhitelist => dcdt_safe_add_token_to_whitelist
        setMultiTransferOnDcdtSafe => set_multi_transfer_on_dcdt_safe
        setDcdtSafeOnMultiTransfer => set_dcdt_safe_on_multi_transfer
        dcdtSafeRemoveTokenFromWhitelist => dcdt_safe_remove_token_from_whitelist
        dcdtSafeSetMaxTxBatchSize => dcdt_safe_set_max_tx_batch_size
        dcdtSafeSetMaxTxBatchBlockDuration => dcdt_safe_set_max_tx_batch_block_duration
        dcdtSafeSetMaxBridgedAmountForToken => dcdt_safe_set_max_bridged_amount_for_token
        multiTransferDcdtSetMaxBridgedAmountForToken => multi_transfer_dcdt_set_max_bridged_amount_for_token
        multiTransferDcdtSetMaxRefundTxBatchSize => multi_transfer_dcdt_set_max_refund_tx_batch_size
        multiTransferDcdtSetMaxRefundTxBatchBlockDuration => multi_transfer_dcdt_set_max_refund_tx_batch_block_duration
        multiTransferDcdtSetWrappingContractAddress => multi_transfer_dcdt_set_wrapping_contract_address
        getQuorum => quorum
        getNumBoardMembers => num_board_members
        getRequiredStakeAmount => required_stake_amount
        getAmountStaked => amount_staked
        getSlashAmount => slash_amount
        getSlashedTokensAmount => slashed_tokens_amount
        getLastExecutedEthBatchId => last_executed_eth_batch_id
        getLastExecutedEthTxId => last_executed_eth_tx_id
        getErc20AddressForTokenId => erc20_address_for_token_id
        getTokenIdForErc20Address => token_id_for_erc20_address
        getDcdtSafeAddress => dcdt_safe_address
        getMultiTransferDcdtAddress => multi_transfer_dcdt_address
        getProxyAddress => proxy_address
        getCurrentTxBatch => get_current_tx_batch
        getBatch => get_batch
        getCurrentRefundBatch => get_current_refund_batch
        wasActionExecuted => was_action_executed
        wasTransferActionProposed => was_transfer_action_proposed
        getActionIdForTransferBatch => get_action_id_for_transfer_batch
        wasSetCurrentTransactionBatchStatusActionProposed => was_set_current_transaction_batch_status_action_proposed
        getActionIdForSetCurrentTransactionBatchStatus => get_action_id_for_set_current_transaction_batch_status
        signed => signed
        userRole => user_role
        getAllBoardMembers => get_all_board_members
        getAllStakedRelayers => get_all_staked_relayers
        getActionSignerCount => get_action_signer_count
        getActionValidSignerCount => get_action_valid_signer_count
        quorumReached => quorum_reached
        getActionLastIndex => get_action_last_index
        getActionData => get_action_data
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

dharitri_sc_wasm_adapter::async_callback_empty! {}
