[package]
name = "bridged-tokens-wrapper-meta"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.bridged-tokens-wrapper]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "=0.52.3"
default-features = false
